# config.yaml
dataset:
  class_names: ["MSA", "PD"] #["MSA-P", "MSA-C"],["MSA-P", "PD"],["PD", "MSA-P", "MSA-C"]

data_splitting:
  random_seed: 42
  val_set_size: 0.2
  test_set_size: 0.10
  num_folds: 7

data_augmentation:
  resize_spatial_size: [256,256]  # Tuple becomes list in YAML
  rand_flip_prob: 0.3
  rand_flip_spatial_axes: [0, 1]
  rand_rotate90_prob: 0.3
  rand_rotate90_max_k: 3
  rand_gaussian_noise_prob: 0.4
  rand_gaussian_noise_mean: 0.0
  rand_gaussian_noise_std: 0.1

data_loading:
  batch_size: 8
  num_workers: 0

model:
  model_name: "base"
  spatial_dims: 2
  in_channels: 3
  out_channels: 2
  dropout_prob: 0.1
  library: "monai"

training:
  num_epochs: 50
  early_stopping_patience: 17
  mixup_alpha: 0
  oversample: true
  undersample: false
  weighted_loss: false
  fine_tuning: false
  transfer_learning: true
  freezed_layerIndex: null  # null in YAML = None in Python
  

optimizer:
  learning_rate: 1e-4  # Will be adjusted automatically
  optimizer_name: "Adam"
  weight_decay: 2e-5

scheduler:
  scheduler_name: "ReduceLROnPlateau"
  factor: 0.5
  scheduler_patience: 9
  threshold: 1e-4
  min_lr: 1e-8