_base_: base.yaml 
# inherits from base.yaml overwriting all the parameters following this line if they exist

# Data Splitting
data_splitting:
  random_seed: 42
  val_set_size: 0.15
  test_set_size: 0.1
  # num_folds: 7  # Changed from base

# Data Loading
data_loading:
  batch_size: 32  # Custom batch size for DenseNet
  num_workers: 0  # Increased workers

model:
  model_name: "Densenet169"  # Specific model name
  spatial_dims: 2
  in_channels: 4
  out_channels: 2 #TODO should be called num_classes
  library: "monai"  # Using MONAI for 4 channels support
# Training
training:
  num_epochs: 125
  early_stopping_patience: 40
  mixup_alpha: 0
  oversample: true
  undersample: false
  weighted_loss: false
  fine_tuning: false
  transfer_learning: false
  freezed_layerIndex: null

# Optimizer
optimizer:
  learning_rate: 2e-4  # Custom learning rate
  optimizer_name: "AdamW"  # Changed optimizer
  weight_decay: 1e-4
  patience: 25 

data_augmentation:
  use_color_transforms: false