_base_: base.yaml

# Data Splitting
data_splitting:
  random_seed: 42
  # num_folds: 7  # Changed from base

# Data Loading
data_loading:
  batch_size: 16  # Custom batch size for DenseNet
  num_workers: 4  

model:
  model_name: "Densenet121"  # Specific model name
  library: "monai"  # Using MONAI for 4 channels support
  
# Training
training:
  num_epochs: 210
  early_stopping_patience: 35
  # mixup_alpha:   # Added mixup
  freezed_layerIndex: null

# Optimizer
optimizer:
  learning_rate: 2e-4  # Custom learning rate
  optimizer_name: "AdamW"  # Changed optimizer
  weight_decay: 1e-4
  patience: 25


