_base_: base.yaml

data_loading:
  batch_size: 16
  num_workers: 2

model:
  model_name: "EfficientNet"
  spatial_dims: 2
  in_channels: 4
  out_channels: 2
  
training:
  num_epochs: 100
  early_stopping_patience: 19
  mixup_alpha: 0
  oversample: true
  undersample: false
  weighted_loss: false
  fine_tuning: false
  transfer_learning: true
  freezed_layerIndex: null

optimizer:
  learning_rate: 2e-4
  optimizer_name: "AdamW"
  weight_decay: 1e-4

data_augmentation:
  use_color_transforms: false
