_base_: base.yaml

data_loading:
  batch_size: 32
  num_workers: 2

model:
  model_name: "SimpleCNN"
  spatial_dims: 2
  in_channels: 4
  out_channels: 2
  
training:
  num_epochs: 100
  early_stopping_patience: 15
  mixup_alpha: 0
  oversample: false
  undersample: false
  weighted_loss: false
  fine_tuning: false
  transfer_learning: false
  freezed_layerIndex: null

optimizer:
  learning_rate: 1e-3
  optimizer_name: "Adam"
  weight_decay: 1e-5

data_augmentation:
  use_color_transforms: false
